image: node:10.22.0-alpine

cache:
  paths:
    - node_modules

stages:
  - test
  - build

Test:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn test:unit

Build:
  stage: build
  artifacts:
    paths:
      - dist/
  before_script:
    - yarn install
  script:
    - yarn build
